### ISSUE TITLE
Lemmy ListPosts results limited to 50

### ISSUE THREAD

**Issue by BreadMakesYouFull** [mrusme/neonmodem#37]
Lemmy post results are limited to 50 which results in a lot of empty communities (forums) when you have many subscriptions.
Probably need to split the go request in ``system/lemmy/lemmy.go func ListPosts``  into multiple requests, bumping the limit number directly will not succeed, but not experienced enough to do this myself.

**Comment by BreadMakesYouFat** [comment]
Worked out how ListPosts worked and combined with the changes from #32's pull request, so this can probably closed :)
