### ISSUE TITLE
[Lemmy] Nested replies don't specifically mention who posted parent reply.

### ISSUE THREAD

**Issue by Sir-Ivysaur** [mrusme/neonmodem#50]
Replies all mention the OP. Even replies to replies. Like so:

![image](https://github.com/mrusme/neonmodem/assets/114919973/8e00c0b1-fc25-4bbd-9f1a-d9721bea0349)

Here's what it's supposed to look like:

![image](https://github.com/mrusme/neonmodem/assets/114919973/ca801032-aab4-4cc2-b3b9-d49581026f57)

Nested replies should probably say '`<user3> writes in reply to <user2>`', instead of '`<user3> writes in reply to <user1>`'. Or maybe do indents like Lemmy-ui does.

**Comment by mrusme** [comment]
My two cents: Indents will get messy on the CLI, as they can get very deep on Lemmy. I'd suggest using the `in reply to <user2>` variant.
