### ISSUE TITLE
Typing 'n' character while entering filter text opens the new post dialog

### ISSUE THREAD

**Issue by jship** [mrusme/neonmodem#52]
While entering the text for a filter, e.g. if I wanted to look for posts with `new` in the title, as soon as I type the `n` character, the dialog for creating a new post opens.

The filter searching is case-insensitive, so this issue can be worked around by typing capital `N` instead of `n`, and entry of the filter text can continue.

**Comment by jship** [comment]
It's possible the source of the issue may be related or the same as #42.

**Comment by JPRuskin** [comment]
For me, hitting escape to quit the filter quits the application. Possibly all main handling is being applied?
